on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: Ingest to Observe
    steps:
      - uses: actions/checkout@v2
      - id: ingest-observe
        uses: highb/observe-action@main
        with:
          content: '{ "Amazing json document": "Wow" }'
          customer-id: ${{ secrets.OBSERVE_CUSTOMER_ID }}
          ingest-token: ${{ secrets.OBSERVE_TOKEN }} # This is fake
